version: '3.8'

services:
  web1:
    build: .
    image: leilao:latest
    networks:
      - app-network
    expose:
      - "8000"
    environment:
      - TZ=America/Sao_Paulo

  web2:
    build: .
    image: leilao:latest
    networks:
      - app-network
    expose:
      - "8000"
    environment:
      - TZ=America/Sao_Paulo

  web3:
    build: .
    image: leilao:latest
    networks:
      - app-network
    expose:
      - "8000"
    environment:
      - TZ=America/Sao_Paulo

  redis-manager:
    image: redis:alpine
    networks:
      - app-network
    deploy:
      replicas: 1
    command: redis-server --appendonly yes

  redis-worker:
    image: redis:alpine
    networks:
      - app-network
    deploy:
      replicas: 2
    command: redis-server --replicaof redis-manager 6379 --appendonly yes

  redis-pub-sub:
    image: redis:alpine
    networks:
      - app-network
    deploy:
      replicas: 1
    command: redis-server --notify-keyspace-events Ex --appendonly yes

  haproxy:
    image: haproxy:latest
    networks:
      - app-network
    ports:
      - "80:80"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg

networks:
  app-network:
    driver: overlay
